-- Migration: Add referrals table for the referral / invite program
-- Created: 2026-08-06
-- Feature: Users generate unique invite codes, track pending/claimed referrals
--
-- Each row is one invite code issued by a referrer. `code` is an 8-char
-- alphanumeric string (UUID-derived, generated by the backend) and is unique.
-- `status` transitions pending → claimed when a new user signs up with the code.

-- Enable pgcrypto for UUID generation (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Main referrals table
CREATE TABLE IF NOT EXISTS referrals (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    referrer_id     TEXT NOT NULL,              -- users.id of the inviter
    code            TEXT NOT NULL UNIQUE,       -- 8-char alphanumeric invite code
    referred_email  TEXT,                       -- email of the invited person (set on claim)
    status          TEXT NOT NULL DEFAULT 'pending',  -- pending | claimed
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at      TIMESTAMPTZ                 -- set when the code is claimed
);

-- Stats per referrer (invites sent, claimed/pending breakdown)
CREATE INDEX IF NOT EXISTS idx_referrals_referrer_status
    ON referrals (referrer_id, status, created_at DESC);

-- Fast claim lookup by referred email (optional)
CREATE INDEX IF NOT EXISTS idx_referrals_referred_email
    ON referrals (referred_email);

-- Enable Row-Level Security
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;

-- Users can view their own referral codes
CREATE POLICY "Users can view own referrals"
    ON referrals FOR SELECT
    USING (auth.uid()::text = referrer_id);

-- Service role bypass (backend API uses service/anon key)
CREATE POLICY "Service role full access"
    ON referrals FOR ALL
    USING (true)
    WITH CHECK (true);
